" Turn on syntax highlighting
syntax on
filetype plugin indent on
set termguicolors

" air-line
let g:airline_powerline_fonts = 1

" Don't use italics (doesn't work)
let g:dracula_italic = 0

" Set Space as leader key
let mapleader = "\<Space>"

" Mix format on save
let g:mix_format_on_save = 1

" Fix files with prettier, and then ESLint.
let g:ale_fixers = ['prettier', 'eslint', 'stylelint']

" Set this variable to 1 to fix files when you save them.
let g:ale_fix_on_save = 1

" Access vimrc and then source it
nmap <leader>vr :sp $MYVIMRC<cr>
nmap <leader>so :source $MYVIMRC<cr>

" Override default scroll down/up when text wraps
nmap k gk
nmap j gj

" Map ^ to 0
nmap 0 ^

" Map :Files to ctl+p
nnoremap <C-p> :GFiles<Cr>

" Map :Ag to ctrl + g
nnoremap <C-g> :Ag<Cr>

" Copy relative path of file to clipboard
nnoremap <leader>cf :!echo -n % \| pbcopy<cr>

" Copy to system clipboard
set clipboard=unnamed

" Show line numbers
set number

" Keep 10 lines below and above the cursor
set scrolloff=10

" Show current line number
set number

" Show relative line numbers
set relativenumber

" Open new split panes to right and bottom
set splitbelow
set splitright

" Fzf
let $FZF_DEFAULT_COMMAND = 'rg --files --ignore-case --hidden -g "!{.git,node_modules,vendor,_build}/*"'
let $FZF_DEFAULT_OPTS="--height=50% --layout=reverse --info=inline --preview='cat {}' --preview-window=right:60%:wrap"
command! -bang -nargs=? -complete=dir Files
     \ call fzf#vim#files(<q-args>, fzf#vim#with_preview(), <bang>0)

" Plugins
call plug#begin()

Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'elixir-editors/vim-elixir'
Plug 'mhinz/vim-mix-format'
Plug 'vim-test/vim-test'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'Yggdroot/indentLine'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'sheerun/vim-polyglot'
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'elixir-lsp/coc-elixir', {'do': 'yarn install && yarn prepack'}
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'dense-analysis/ale'

call plug#end()

colorscheme dracula
