set nocompatible

" Plugind
call plug#begin()

Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'elixir-editors/vim-elixir'
Plug 'mhinz/vim-mix-format'
Plug 'tpope/vim-surround'
Plug 'Yggdroot/indentLine'
Plug 'sheerun/vim-polyglot'
Plug 'itchyny/lightline.vim'
Plug 'sonph/onehalf', {'rtp': 'vim/'}

call plug#end()

" General
filetype plugin indent on
set tabstop=2
set softtabstop=2
set expandtab
set shiftwidth=2
inoremap jk <ESC>

" Set Space as leader key
let mapleader = "\<Space>"

" Mix format on save
let g:mix_format_on_save = 1
let g:mix_format_silent_errors = 1

" Access vimrc and then source it
nmap <leader>vr :sp $MYVIMRC<cr>
nmap <leader>so :source $MYVIMRC<cr>

"Remove whitespace at the end ofthe line
autocmd BufWritePre * :%s/\s\+$//e

" Override default scroll down/up when text wraps
" nmap k gk
" nmap j gj

" Map ^ to 0
nmap 0 ^

" Map :Files to ctl+p
nnoremap <C-p> :Files<Cr>

" Map :Ag to ctrl + g
nnoremap <C-g> :Ag<Cr>

" Copy relative path of file to clipboard
nnoremap <leader>cf :!echo -n % \| pbcopy<cr>

" Copy to system clipboard
set clipboard=unnamed

" Show line numbers
set number

" Keep 10 lines below and above the cursor
set scrolloff=10

" Show relative line numbers
set relativenumber

" Open new split panes to right and bottom
set splitbelow
set splitright

syntax on
set t_Co=256
set cursorline
colorscheme onehalfdark
let g:airline_theme='onehalfdark'
let g:lightline = { 'colorscheme': 'onehalfdark' }
if exists('+termguicolors')
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
  hi Linebr ctermbg=NONE guibg=NONE
endif
